Repository Cavonstavant/PLAZAAAAAAAAAAAAAAAAAAAAAAA, pull requests merged in 2022-05, with the labels that each got.

#19 Arguments Handling
  .gitignore
  src/Parser/ArgumentsParser/ArgumentsParser.cpp
  src/Parser/ArgumentsParser/ArgumentsParser.hpp
  src/Parser/CMakeLists.txt
  src/main.cpp
Labels: documentation, good first issue

#23 Using the parameter argc instead of calculating the size of the vector arguments
  src/Parser/ArgumentsParser/ArgumentsParser.cpp
  src/Parser/ArgumentsParser/ArgumentsParser.hpp
  src/main.cpp
Labels: documentation, enhancement

#17 Feature/15 ipc create wrapper class for unix message queue
  .github/workflows/doc_build.yml
  .gitignore
  CMakeLists.txt
  src/CMakeLists.txt
  src/MessageQueue/CMakeLists.txt
  src/MessageQueue/MessageQueue.cpp
  src/MessageQueue/MessageQueue.hpp
  src/logger/CMakeLists.txt
  src/logger/Exception.cpp
  src/logger/Exception.hpp
  src/logger/Logger.cpp
  src/logger/Logger.hpp
  tests/CMakeLists.txt
  tests/unit_tests/CMakeLists.txt
  tests/unit_tests/MessageQueue/CMakeLists.txt
  tests/unit_tests/MessageQueue/MessageQueue_test.cpp
  tests/unit_tests/Parser/CMakeLists.txt
  tests/unit_tests/Parser/Parser_test.cpp
Labels: IPC

#28 [*] Update MessageQueue to wrap POSIX message queue instead of System V
  .gitignore
  src/CMakeLists.txt
  src/MessageQueue/MessageQueue.cpp
  src/MessageQueue/MessageQueue.hpp
  src/logger/Exception.hpp
  src/main.cpp
  tests/unit_tests/CMakeLists.txt
  tests/unit_tests/MessageQueue/CMakeLists.txt
  tests/unit_tests/MessageQueue/MessageQueue_test.cpp
Labels: bug, IPC

#35 Adding Exceptions on Arguments Parser
  src/Parser/ArgumentsParser/ArgumentsParser.cpp
  src/Parser/CMakeLists.txt
  src/logger/Exception.hpp
Labels: enhancement

#37 Implementation of the Plazza Class
  src/CMakeLists.txt
  src/Core/CMakeLists.txt
  src/Core/Plazza.cpp
  src/Core/Plazza.hpp
  src/main.cpp
Labels: documentation, enhancement

#49 Moving Arguments Parser in Plazza namespace, close #48
  src/Parser/ArgumentsParser/ArgumentsParser.cpp
  src/Parser/ArgumentsParser/ArgumentsParser.hpp
  src/main.cpp
Labels: enhancement

#52 Add Try and Catch on main
  src/main.cpp
Labels: bug

#43 pizza structure and pizza size enum
  src/Core/CMakeLists.txt
  src/Core/Pizza.hpp
Labels: enhancement

#58 InputParser - fix pizza name
  src/Parser/InputParser/InputParser.cpp
Labels: fix

#62 Missing throw when an exception occurs
  src/Parser/InputParser/InputParser.cpp
Labels: bug

#71 Create kitchen class
  src/CMakeLists.txt
  src/Core/CMakeLists.txt
  src/Core/Kitchen/CMakeLists.txt
  src/Core/Kitchen/Kitchen.cpp
  src/Core/Kitchen/Kitchen.hpp
  src/Core/Plazza.cpp
  src/Logger/CMakeLists.txt
  src/Logger/Exception.cpp
  src/Logger/Exception.hpp
  src/Logger/Logger.cpp
  src/Logger/Logger.hpp
Labels: enhancement

#78 [*] Add gcov support
  .github/workflows/cmake.yml
  .github/workflows/unit_tests.yml
  .gitignore
  CMakeLists.txt
  README.md
Labels: enhancement

#76 Adding Plazza Fridge
  src/Core/Kitchen/Kitchen.cpp
  src/Core/Kitchen/Kitchen.hpp
Labels: enhancement

#85 Naming Ingredients on Kitchen Fridge, close #84
  src/Core/Kitchen/Kitchen.cpp
  src/Core/Kitchen/Kitchen.hpp
  src/Core/Plazza.cpp
Labels: fix

#93 Add a blocking thread on the message queue
  src/CMakeLists.txt
  src/Core/CMakeLists.txt
  src/Core/Kitchen/CMakeLists.txt
  src/Core/Kitchen/Kitchen.cpp
  src/Core/Kitchen/Kitchen.hpp
  src/Core/Plazza.cpp
  src/Core/Plazza.hpp
  src/MessageQueue/MessageQueue.cpp
  src/MessageQueue/MessageQueue.hpp
  src/main.cpp
  tests/unit_tests/MessageQueue/CMakeLists.txt
  tests/unit_tests/MessageQueue/MessageQueue_test.cpp
Labels: enhancement

#98 Add Multiplier for Cooking Time in the Kitchen, close #97
  src/Core/Kitchen/Kitchen.hpp
  src/Core/Plazza.cpp
Labels: enhancement, fix

#105 [*] Update thread pool to take pizzas as order instead of functions
  src/CMakeLists.txt
  src/Core/CMakeLists.txt
  src/Core/Cook/CMakeLists.txt
  src/Core/Kitchen/CMakeLists.txt
  src/Core/Kitchen/Kitchen.cpp
  src/Core/Kitchen/Kitchen.hpp
Labels: enhancement, fix, Kitchen

#113 Can open more messages queues
  src/Core/Plazza.cpp
  src/Core/Plazza.hpp
Labels: enhancement, fix

#118 Add Mutex on Kitchen Threads
  src/Core/Kitchen/Kitchen.cpp
  src/Core/Kitchen/Kitchen.hpp
Labels: enhancement

#119 Kill the child process
  src/Core/Plazza.cpp
  src/Core/Plazza.hpp
Labels: enhancement, fix

#122 Remove useless ingredient
  src/Core/Kitchen/Kitchen.cpp
  src/Core/Kitchen/Kitchen.hpp
  src/Core/Parser/InputParser/InputParser.cpp
Labels: enhancement, fix

#123 115 Logger - Create separate logging mechanisms for pizzas and exceptions
  src/Logger/CMakeLists.txt
  src/Logger/Logger.cpp
  src/Logger/PizzaLogger.cpp
  src/Logger/PizzaLogger.hpp
  src/main.cpp
  tests/unit_tests/CMakeLists.txt
  tests/unit_tests/Logger/CMakeLists.txt
  tests/unit_tests/Logger/Logger_test.cpp
Labels: enhancement

#125 Fix Args Parser
  src/Core/Kitchen/Kitchen.hpp
  src/Core/Parser/ArgumentsParser/ArgumentsParser.cpp
  src/Core/Parser/ArgumentsParser/ArgumentsParser.hpp
  src/Core/Plazza.cpp
  src/Core/Plazza.hpp
Labels: enhancement, fix

#127 [*] Update pizza logging format
  src/Logger/PizzaLogger.cpp
  src/main.cpp
  tests/unit_tests/Logger/Logger_test.cpp
Labels: bug

#143 Ut/ut - Unit tests
  .github/workflows/unit_tests.yml
  tests/unit_tests/CMakeLists.txt
  tests/unit_tests/Cook/CMakeLists.txt
  tests/unit_tests/Cook/Cook_test.cpp
  tests/unit_tests/Kitchen/CMakeLists.txt
  tests/unit_tests/Kitchen/Kitchen_test.cpp
  tests/unit_tests/Logger/Logger_test.cpp
Labels: enhancement
